apiVersion: v1
kind: ConfigMap
metadata:
  name: uperf-client-cm
data:
  uperf.xml: >
    <?xml version= 1.0?>
      <profile name="stream-tcp-64-64-1">
      <group nthreads="1">
          <transaction iterations="1">
            <flowop type="connect" options="remotehost=<UPDATEME>:30000 protocol=tcp port=30001"/>
          </transaction>
          <transaction duration="60">
            <flowop type=write options="count=16 size=64"/>
          </transaction>
          <transaction iterations="1">
            <flowop type=disconnect />
          </transaction>
      </group>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uperf-client 
spec:
  selector:
    matchLabels:
      app: uperf-client
  template:
    metadata:
      labels:
        app: uperf-client 
    spec:
      containers:
      - name: uperf-client
        image: quay.io/krvoora_ocm/windows:uperf-simply
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: c:\uperf\uperf
        command:
        - powershell.exe
        - -command
        - python c:\uperf\uperf.py
      volumes:
      - name: config-volume
        configMap:
          name: uperf-client-cm
        resources:
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
      - key: "os"
        value: "Windows"
